apiVersion: v2
name: supercards-stack
description: Umbrella chart for Supercards app + PostgreSQL
type: application
version: 0.1.0
dependencies:
  - name: supercards
    version: "0.1.0"
    repository: "file://../supercards"

  - name: postgresql
    version: "18.5.14"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
