apiVersion: v1
kind: Service
metadata:
  name: {{ include "supercards.fullname" . }}
  labels:
    {{- include "supercards.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "supercards.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
