replicaCount: 1

image:
  repository: docker.id/serbriss/supercards
  tag: "0.0.1-SNAPSHOT"
  pullPolicy: Never

service:
  type: ClusterIP
  port: 8199

ingress:
  enabled: false
  className: ""
  host: supercards.local

resources: {}

db:
  jdbcUrl: ""
  username: postgres
  password: postgres

dbSecret:
  name: supercards-db-secret

configMap:
  name: supercards-config
